/*
 * Notification Actions
 */

export const SHOW_NOTIFICATION = "SHOW_NOTIFICATION";
export const CLEAR_NOTIFICATION = "CLEAR_NOTIFICATION";

/*
 * User Actions
 */

export const UPDATE_USER_OBJECT_CREATE = "UPDATE_USER_OBJECT_CREATE";
export const UPDATE_USER_OBJECT_LOGIN = "UPDATE_USER_OBJECT_LOGIN";
export const CLEAR_USER_OBJECT = "CLEAR_USER_OBJECT";

/*
 * Merm Actions
 */

export const UPDATE_MERM_LIST = "UPDATE_MERM_LIST";
export const CLEAR_MERM_LIST = "CLEAR_MERM_LIST";

export const UPDATE_DETAILED_MERM = "UPDATE_DETAILED_MERM";
export const UPDATE_EDIT_DETAILED_MERM = "UPDATE_EDIT_DETAILED_MERM";
export const UPDATE_DETAILED_MERM_COMMENTS = "UPDATE_DETAILED_MERM_COMMENTS";
export const CLEAR_DETAILED_MERM = "CLEAR_DETAILED_MERM";

/*
 * Request Status Actions
 */

export const GET_REQUEST_INITIATED = "GET_REQUEST_INITIATED";
export const GET_REQUEST_SUCCESS = "GET_REQUEST_SUCCESS";
export const GET_REQUEST_FAILURE = "GET_REQUEST_FAILURE";
export const POST_REQUEST_INITIATED = "POST_REQUEST_INITIATED";
export const POST_REQUEST_SUCCESS = "POST_REQUEST_SUCCESS";
export const POST_REQUEST_FAILURE = "POST_REQUEST_FAILURE";
export const PUT_REQUEST_INITIATED = "PUT_REQUEST_INITIATED";
export const PUT_REQUEST_SUCCESS = "PUT_REQUEST_SUCCESS";
export const PUT_REQUEST_FAILURE = "PUT_REQUEST_FAILURE";
export const DELETE_REQUEST_INITIATED = "DELETE_REQUEST_INITIATED";
export const DELETE_REQUEST_SUCCESS = "DELETE_REQUEST_SUCCESS";
export const DELETE_REQUEST_FAILURE = "DELETE_REQUEST_FAILURE";
export const RESET_REQUEST_STATUS = "RESET_REQUEST_STATUS";
