export const SAVE_FUEL_SAVINGS = "SAVE_FUEL_SAVINGS";
export const CALCULATE_FUEL_SAVINGS = "CALCULATE_FUEL_SAVINGS";

/*
 * User Actions
 */

export const UPDATE_USER_OBJECT = "UPDATE_USER_OBJECT";
export const CLEAR_USER_OBJECT = "CLEAR_USER_OBJECT";

/*
 * Request Status Actions
 */

export const GET_REQUEST_INITIATED = "GET_REQUEST_INITIATED";
export const GET_REQUEST_SUCCESS = "GET_REQUEST_SUCCESS";
export const GET_REQUEST_FAILURE = "GET_REQUEST_FAILURE";
export const POST_REQUEST_INITIATED = "POST_REQUEST_INITIATED";
export const POST_REQUEST_SUCCESS = "POST_REQUEST_SUCCESS";
export const POST_REQUEST_FAILURE = "POST_REQUEST_FAILURE";
export const PUT_REQUEST_INITIATED = "PUT_REQUEST_INITIATED";
export const PUT_REQUEST_SUCCESS = "PUT_REQUEST_SUCCESS";
export const PUT_REQUEST_FAILURE = "PUT_REQUEST_FAILURE";
export const DELETE_REQUEST_INITIATED = "DELETE_REQUEST_INITIATED";
export const DELETE_REQUEST_SUCCESS = "DELETE_REQUEST_SUCCESS";
export const DELETE_REQUEST_FAILURE = "DELETE_REQUEST_FAILURE";
export const RESET_REQUEST_STATUS = "RESET_REQUEST_STATUS";
