/*
 * Notification Actions
 */

export const SHOW_NOTIFICATION = "SHOW_NOTIFICATION";
export const CLEAR_NOTIFICATION = "CLEAR_NOTIFICATION";

/*
 * User Actions
 */

export const UPDATE_USER_OBJECT_CREATE = "UPDATE_USER_OBJECT_CREATE";
export const UPDATE_USER_OBJECT_LOGIN = "UPDATE_USER_OBJECT_LOGIN";
export const CLEAR_USER_OBJECT = "CLEAR_USER_OBJECT";

/*
 * Merm Actions
 */

export const UPDATE_MERM_LIST = "UPDATE_MERM_LIST";
export const CLEAR_MERM_LIST = "CLEAR_MERM_LIST";

export const UPDATE_DETAILED_MERM = "UPDATE_DETAILED_MERM";
export const UPDATE_EDIT_DETAILED_MERM = "UPDATE_EDIT_DETAILED_MERM";
export const UPDATE_DETAILED_MERM_COMMENTS = "UPDATE_DETAILED_MERM_COMMENTS";
export const UPDATE_DETAILED_MERM_TAGS = "UPDATE_DETAILED_MERM_TAGS";
export const UPDATE_DETAILED_MERM_REMOVE_TAG = "UPDATE_DETAILED_MERM_REMOVE_TAG";
export const CLEAR_DETAILED_MERM = "CLEAR_DETAILED_MERM";

export const UPDATE_SEARCH_RESULTS_LIST = "UPDATE_SEARCH_RESULTS_LIST";
export const CLEAR_SEARCH_RESULTS_LIST = "CLEAR_SEARCH_RESULTS_LIST";

/*
 * Request Status Actions
 */

export const REQUEST_INITIATED = "REQUEST_INITIATED";
export const REQUEST_SUCCESS = "REQUEST_SUCCESS";
export const REQUEST_FAILURE = "REQUEST_FAILURE";
export const RESET_REQUEST_STATUS = "RESET_REQUEST_STATUS";
